version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    container_name: jonahgcarpenter/aprilslilpugs-www
    command: npm run build

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    container_name: jonahgcarpenter/aprilslilpugs-api
    depends_on:
      - frontend

# docker-compose build